version: "3"

services:
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data